spring:
  application:
    name: triage-academico

  datasource:
    url: jdbc:h2:mem:triagedb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: method

default-users:
  users:
    - username: admin@uniquindio.edu.co
      password: admin123
      role: ADMIN
    - username: estudiante@uniquindio.edu.co
      password: estudiante123
      role: USER