spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/triage_academico

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: method